[project]
name = "mindmapp-generation1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiofiles==25.1.0",
    "aiohappyeyeballs==2.6.1",
    "aiohttp==3.13.2",
    "aiosignal==1.4.0",
    "altair==5.5.0",
    "annotated-types==0.7.0",
    "anyio==4.11.0",
    "appdirs==1.4.4",
    "asgiref==3.10.0",
    "attrs==25.4.0",
    "beautifulsoup4==4.14.2",
    "bidict==0.23.1",
    "blinker==1.9.0",
    "boto3-stubs==1.40.72",
    "botocore-stubs==1.40.72",
    "bs4==0.0.2",
    "cachetools==6.2.1",
    "certifi==2025.11.12",
    "charset-normalizer==3.4.4",
    "chromium==0.0.0",
    "click==8.3.0",
    "colorama==0.4.6",
    "cssselect==1.3.0",
    "distro==1.9.0",
    "dotenv==0.9.9",
    "exceptiongroup==1.3.0",
    "fake-useragent==2.2.0",
    "fastuuid==0.14.0",
    "filelock==3.20.0",
    "flask==3.1.2",
    "flask-socketio==5.5.1",
    "frozenlist==1.8.0",
    "fsspec==2025.10.0",
    "gitdb==4.0.12",
    "gitpython==3.1.45",
    "google-ai-generativelanguage>=0.6.15",
    "google-api-core>=2.25.2",
    "google-api-python-client>=2.187.0",
    "google-auth>=2.43.0",
    "google-auth-httplib2>=0.2.1",
    "google-generativeai>=0.8.5",
    "googleapis-common-protos>=1.72.0",
    "greenlet==3.1.1",
    "grpcio==1.75.1",
    "grpcio-status==1.71.2",
    "h11==0.16.0",
    "h2==4.3.0",
    "hf-xet==1.2.0",
    "hpack==4.1.0",
    "httpcore==1.0.9",
    "httplib2==0.31.0",
    "httpx==0.28.1",
    "huggingface-hub==1.1.4",
    "hypercorn==0.17.3",
    "hyperframe==6.1.0",
    "idna==3.11",
    "importlib-metadata==8.7.0",
    "iniconfig==2.3.0",
    "itsdangerous==2.2.0",
    "jinja2==3.1.6",
    "jiter==0.12.0",
    "joblib==1.5.2",
    "jsonpatch==1.33",
    "jsonpointer==3.0.0",
    "jsonschema==4.25.1",
    "jsonschema-specifications==2025.9.1",
    "langchain==1.0.5",
    "langchain-core==1.0.4",
    "langchain-openai==1.0.2",
    "langgraph==1.0.3",
    "langgraph-checkpoint==3.0.1",
    "langgraph-prebuilt==1.0.2",
    "langgraph-sdk==0.2.9",
    "langsmith==0.4.42",
    "litellm==1.79.3",
    "lxml==6.0.2",
    "lxml-html-clean==0.4.3",
    "markdown-it-py==4.0.0",
    "markupsafe==3.0.3",
    "mdurl==0.1.2",
    "multidict==6.7.0",
    "mypy-boto3-bedrock-runtime==1.40.62",
    "narwhals==2.8.0",
    "numpy==2.2.6",
    "openai==2.7.2",
    "opik==1.9.10",
    "orjson==3.11.4",
    "ormsgpack==1.12.0",
    "packaging==25.0",
    "pandas==2.3.3",
    "parse==1.20.2",
    "pillow==11.3.0",
    "playwright==1.48.0",
    "pluggy==1.6.0",
    "priority==2.0.0",
    "propcache==0.4.1",
    "proto-plus==1.26.1",
    "protobuf==5.29.5",
    "pyarrow==21.0.0",
    "pyasn1==0.6.1",
    "pyasn1-modules==0.4.2",
    "pydantic==2.12.4",
    "pydantic-core==2.41.5",
    "pydantic-settings==2.12.0",
    "pydeck==0.9.1",
    "pyee==12.0.0",
    "pygments==2.19.2",
    "pyparsing==3.2.5",
    "pyppeteer==0.0.25",
    "pyquery==2.0.1",
    "pytest==9.0.1",
    "python-dateutil==2.9.0.post0",
    "python-dotenv==1.2.1",
    "python-engineio==4.12.3",
    "python-socketio==5.14.3",
    "pytz==2025.2",
    "pyyaml==6.0.3",
    "quart==0.20.0",
    "rapidfuzz==3.14.3",
    "referencing==0.37.0",
    "regex==2025.11.3",
    "requests==2.32.5",
    "requests-html==0.10.0",
    "requests-toolbelt==1.0.0",
    "rich==14.2.0",
    "rpds-py==0.28.0",
    "rsa==4.9.1",
    "scikit-learn==1.7.2",
    "scipy==1.15.3",
    "sentry-sdk==2.44.0",
    "shellingham==1.5.4",
    "simple-websocket==1.1.0",
    "six==1.17.0",
    "smmap==5.0.2",
    "sniffio==1.3.1",
    "soupsieve==2.8",
    "taskgroup==0.2.2",
    "tenacity==9.1.2",
    "threadpoolctl==3.6.0",
    "tiktoken==0.12.0",
    "tokenizers==0.22.1",
    "toml==0.10.2",
    "tomli==2.3.0",
    "tornado==6.5.2",
    "tqdm==4.67.1",
    "typer-slim==0.20.0",
    "types-awscrt==0.28.4",
    "types-s3transfer==0.14.0",
    "typing-extensions==4.15.0",
    "typing-inspection==0.4.2",
    "tzdata==2025.2",
    "uritemplate==4.2.0",
    "urllib3==2.5.0",
    "uuid6==2025.0.1",
    "w3lib==2.3.1",
    "waitress==3.0.2",
    "watchdog==6.0.0",
    "websockets==10.4",
    "werkzeug==3.1.3",
    "wsproto==1.2.0",
    "xxhash==3.6.0",
    "yarl==1.22.0",
    "zipp==3.23.0",
    "zstandard==0.25.0",
]
